---
Parameters:
  PrimaryKeyName:
    Type: String
  PrimaryKeyType:
    Type: String
Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: 
            Ref: PrimaryKeyName
          AttributeType:
            Ref: PrimaryKeyType
      KeySchema:
        - KeyType: HASH
          AttributeName:
            Ref: PrimaryKeyName
Output:
  DynamoDBTable:
    Description: DynamoDB table name
    Value: !Ref DynamoDBTable