AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters: 
  name: 
    Type: String
    Default: HelloWorldApi
    Description : Application name
  env:
    Type: String
    Default: development
    Description : Environment

Resources:

  HelloWorldGet:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: functions/index.get
      Runtime: python3.6
      FunctionName: HelloWorldGet
      Description: HelloWorld Get Function
      Tags:
        AppName: !Ref name
        Environment: !Ref env
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Ref: HelloTable
      Environment:
        Variables:
          TABLE_NAME:
            Ref: HelloTable
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: '/{name}'
            Method: get

  HelloWorldList:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: functions/index.list
      Runtime: python3.6
      FunctionName: HelloWorldList
      Description: HelloWorld List Function
      Tags:
        AppName: !Ref name
        Environment: !Ref env
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Ref: HelloTable
      Environment:
        Variables:
          TABLE_NAME:
            Ref: HelloTable
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
      
  HelloWorldPost:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: functions/index.post
      Runtime: python3.6
      FunctionName: HelloWorldPost
      Description: HelloWorld Post Function
      Tags:
        AppName: !Ref name
        Environment: !Ref env
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Ref: HelloTable
      Environment:
        Variables:
          TABLE_NAME:
            Ref: HelloTable
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: '/{name}'
            Method: post
    
  HelloTable:
    Type: 'AWS::Serverless::SimpleTable'
    Properties:
      PrimaryKey:
        Name: name
        Type: String
      Tags:
        AppName: !Ref name
        Environment: !Ref env
        
Outputs:
  ApigwURL:
    Description: API Gateway endpoint URL
    Value:
      'Fn::Sub': >-
        https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/