AWSTemplateFormatVersion: '2010-09-09'
Outputs:
  ApigwURL:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
Parameters:
  env:
    Default: development
    Description: Environment
    Type: String
  name:
    Default: HelloWorldApi
    Description: Application name
    Type: String
Resources:
  HelloTable:
    Properties:
      PrimaryKey:
        Name: name
        Type: String
      Tags:
        AppName:
          Ref: name
        Environment:
          Ref: env
    Type: AWS::Serverless::SimpleTable
  HelloWorldGet:
    Properties:
      CodeUri: s3://gma-test/68ed90d0201df83d9f69b8ca4322494b
      Description: HelloWorld Get Function
      Environment:
        Variables:
          TABLE_NAME:
            Ref: HelloTable
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /{name}
          Type: Api
      Handler: functions/index.get
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: HelloTable
      Runtime: python3.6
      Tags:
        AppName:
          Ref: name
        Environment:
          Ref: env
    Type: AWS::Serverless::Function
  HelloWorldList:
    Properties:
      CodeUri: s3://gma-test/68ed90d0201df83d9f69b8ca4322494b
      Description: HelloWorld List Function
      Environment:
        Variables:
          TABLE_NAME:
            Ref: HelloTable
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /
          Type: Api
      Handler: functions/index.list
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: HelloTable
      Runtime: python3.6
      Tags:
        AppName:
          Ref: name
        Environment:
          Ref: env
    Type: AWS::Serverless::Function
  HelloWorldPost:
    Properties:
      CodeUri: s3://gma-test/68ed90d0201df83d9f69b8ca4322494b
      Description: HelloWorld Post Function
      Environment:
        Variables:
          TABLE_NAME:
            Ref: HelloTable
      Events:
        PostEvent:
          Properties:
            Method: post
            Path: /{name}
          Type: Api
      Handler: functions/index.post
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: HelloTable
      Runtime: python3.6
      Tags:
        AppName:
          Ref: name
        Environment:
          Ref: env
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
